---
apiVersion: v1
kind: Namespace
metadata:
  name: ns1-namespace

---
apiVersion: v1
kind: Namespace
metadata:
  name: ns2-namespace

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dmilan-admin
subjects:
- kind: Group
  name: k8s-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io



---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oidc-ns1
  namespace: ns1-namespace
subjects:
- kind: Group
  name: ns1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: oidc-ns2
  namespace: ns2-namespace
subjects:
- kind: Group
  name: ns2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io


